variables:
  PROXY: "http://proxyout.lanl.gov:8080"
  DEFAULT_CMAKE_OPTS: "-DENABLE_UNIT_TESTS=ON -DENABLE_OPENMP=ON"
  NUM_THREADS: '4'

###############################################################################
# TESTS
##############################################################################

.job_template: &job_definition
  image: ubuntu:latest
  script:
    - echo "cmake options= $DEFAULT_CMAKE_OPTS $CMAKE_OPTS"
    - echo "compiler packages= $COMPILER_PACKAGES"
    - echo "MPI packages= $EXTRA_PACKAGES"
    - export http_proxy="$PROXY"
    - export https_proxy="${http_proxy}"
    - apt-get update
    - apt-get install -y git cmake doxygen python $COMPILER_PACKAGES $EXTRA_PACKAGES
    - export no_proxy=.lanl.gov
    - export GIT_SSL_NO_VERIFY=1
    - git submodule sync
    - git submodule update --init --recursive 
    - git clone https://github.com/USCiLab/cereal.git
    - mkdir build
    - cd build
    - cmake $DEFAULT_CMAKE_OPTS $CMAKE_OPTS -DCereal_INCLUDE_DIR=../cereal/include/ ..
    - make -j$NUM_THREADS VERBOSE=1
    - ctest -V
    - make install
  except:
    - /^release-.*$/

.gnu_template: &gnu_definition
  variables: &gnu_variables
    COMPILER_PACKAGES: "g++ gfortran"
  before_script:
    - export CXX=g++
    - export CC=gcc
    - export FC=gfortran
    - export FFLAGS="-fbounds-check -fbacktrace -ffpe-trap=invalid"

.clang_template: &clang_definition
  variables: &clang_variables
    COMPILER_PACKAGES: "clang gfortran"
  before_script:
    - export CXX=clang++
    - export CC=clang
    - export FC=gfortran
    - export FFLAGS="-fbounds-check -fbacktrace -ffpe-trap=invalid"

.extra_template:
  variables: &extra_variables
    EXTRA_PACKAGES: "libscotch-dev libexodusii-dev liblapacke-dev flex"


###############################################################################
# GNU tests

gnu:minimal:debug:
  <<: *gnu_definition
  variables: 
    <<: *gnu_variables
    CMAKE_OPTS: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Werror"
  <<: *job_definition

gnu:minimal:release:
  <<: *gnu_definition
  variables: 
    <<: *gnu_variables
    CMAKE_OPTS: "-DCMAKE_BUILD_TYPE=Release"
  <<: *job_definition
 
gnu:extra:debug:
  <<: *gnu_definition
  variables: 
    <<: *gnu_variables
    <<: *extra_variables
    CMAKE_OPTS: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Werror"
  <<: *job_definition
  
gnu:extra:release:
  <<: *gnu_definition
  variables: 
    <<: *gnu_variables
    <<: *extra_variables
    CMAKE_OPTS: "-DCMAKE_BUILD_TYPE=Release"
  <<: *job_definition

###############################################################################
# CLANG tests

clang:minimal:debug:
  <<: *clang_definition
  variables: 
    <<: *clang_variables
    CMAKE_OPTS: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Werror"
  <<: *job_definition

clang:minimal:release:
  <<: *clang_definition
  variables: 
    <<: *clang_variables
    CMAKE_OPTS: "-DCMAKE_BUILD_TYPE=Release"
  <<: *job_definition
 
clang:extra:debug:
  <<: *clang_definition
  variables: 
    <<: *clang_variables
    <<: *extra_variables
    CMAKE_OPTS: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Werror"
  <<: *job_definition
 
clang:extra:release:
  <<: *clang_definition
  variables: 
    <<: *clang_variables
    <<: *extra_variables
    CMAKE_OPTS: "-DCMAKE_BUILD_TYPE=Release"
  <<: *job_definition

