variables:
  PROXY: "http://proxyout.lanl.gov:8080"
  NUM_THREADS: '4'

test:flecsi_serial:
  image: flecsi/flecsi:ubuntu_serial
  script:
    - export http_proxy="$PROXY"
    - export https_proxy="${http_proxy}"
    - apt-get update
    - apt-get install -y libboost-all-dev
    - cat .gitmodules
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake -DENABLE_UNIT_TESTS=ON ..
    - make -j${NUM_THREADS}
    - make test -j${NUM_THREADS}
    - make install DESTDIR=${PWD}

test:ubuntu:
  image: ubuntu:latest
  script:
    - export http_proxy="$PROXY"
    - export https_proxy="${http_proxy}"
    - apt-get update
    - apt-get install -y git cmake g++ libboost-all-dev libexodusii-dev pkg-config 
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake -DENABLE_UNIT_TESTS=ON ..
    - make -j-j${NUM_THREADS}
    - make test -j${NUM_THREADS} 
    - make install DESTDIR=${PWD}
