language: generic

sudo: required

services:
- docker

env:
  matrix:
    - DOCKERFILE=fedora COMPILER=gnu BUILD_TYPE=Debug   MINIMAL=ON   
    # - DOCKERFILE=ubuntu COMPILER=gnu BUILD_TYPE=Debug   MINIMAL=ON 
    # - DOCKERFILE=ubuntu COMPILER=gnu BUILD_TYPE=Release MINIMAL=ON 
    # - DOCKERFILE=ubuntu COMPILER=gnu BUILD_TYPE=Debug
    # - DOCKERFILE=ubuntu COMPILER=gnu BUILD_TYPE=Release
    # - DOCKERFILE=ubuntu COMPILER=clang BUILD_TYPE=Debug   MINIMAL=ON 
    # - DOCKERFILE=ubuntu COMPILER=clang BUILD_TYPE=Release MINIMAL=ON 
    # - DOCKERFILE=ubuntu COMPILER=clang BUILD_TYPE=Debug
    # - DOCKERFILE=ubuntu COMPILER=clang BUILD_TYPE=Release
    # - DOCKERFILE=fedora COMPILER=gnu BUILD_TYPE=Debug   MINIMAL=ON 
    # - DOCKERFILE=fedora COMPILER=gnu BUILD_TYPE=Release MINIMAL=ON 
    # - DOCKERFILE=fedora COMPILER=gnu BUILD_TYPE=Debug
    # - DOCKERFILE=fedora COMPILER=gnu BUILD_TYPE=Release
    # - DOCKERFILE=fedora COMPILER=clang BUILD_TYPE=Debug   MINIMAL=ON 
    # - DOCKERFILE=fedora COMPILER=clang BUILD_TYPE=Release MINIMAL=ON 
    # - DOCKERFILE=fedora COMPILER=clang BUILD_TYPE=Debug
    - DOCKERFILE=fedora COMPILER=clang BUILD_TYPE=Release

script:
 - docker build --build-arg MINIMAL=${MINIMAL} 
                --build-arg COMPILER=${COMPILER} 
                --build-arg BUILD_TYPE=${BUILD_TYPE}
                --build-arg COVERAGE=${COVERAGE}
                --build-arg TRAVIS=${TRAVIS} 
                --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH}
                --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT}
                --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
                --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
                -f docker/${DOCKERFILE} docker/

notifications:
  branches:
    only:
      - master
