language: generic

sudo: required

services:
- docker

env:
  matrix:
    - DOCKERFILE=ubuntu MINIMAL=ON COMPILER=gnu BUILD_TYPE=Debug
#    - DOCKERFILE=ubuntu MPI=ON   RUNTIME=mpi          DOCKERHUB=true
#    - DOCKERFILE=ubuntu MPI=ON   RUNTIME=mpi          WERROR=yes
#    - DOCKERFILE=ubuntu MPI=OFF  RUNTIME=serial       DOCKERHUB=true
#    - DOCKERFILE=ubuntu MPI=OFF  RUNTIME=serial       WERROR=yes
#    - DOCKERFILE=ubuntu MPI=OFF  COVERAGE=ON RUNTIME=serial
#    - DOCKERFILE=fedora MINIMAL=ON MPI=OFF RUNTIME=serial
#    - DOCKERFILE=fedora MPI=ON  RUNTIME=mpi           DOCKERHUB=true
#    - DOCKERFILE=fedora MPI=ON  RUNTIME=mpi           WERROR=yes
#    - DOCKERFILE=fedora MPI=OFF RUNTIME=serial        DOCKERHUB=true
#    - DOCKERFILE=fedora MPI=OFF RUNTIME=serial        WERROR=yes
#    - DOCKERFILE=fedora MPI=OFF RUNTIME=serial COVERAGE=ON

script:
 - docker build --build-arg MINIMAL=${MINIMAL} 
                --build-arg COMPILER=${COMPILER} 
                --build-arg BUILD_TYPE=${BUILD_TYPE}
                --build-arg COVERAGE=${COVERAGE}
                --build-arg TRAVIS=${TRAVIS} 
                --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH}
                --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT}
                --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
                --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
                -f docker/${DOCKERFILE} docker/

notifications:
  branches:
    only:
      - master
